version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-18-214-211-47.compute-1.amazonaws.com
            port: '5432'
            database: dn9lsp810m4f
            ssl: true
            user: devyslpazbcafp
            password: 4b0f7f2c0b77e93892a82aaa6f2563dd6c99e6512b34592a49bb9ee880a3d3ad
            migrations: true
